# aptitude/errors.py
class AptitudeError(Exception): ...
class ConfigError(AptitudeError): ...
class IngestionError(AptitudeError): ...
class ProviderError(AptitudeError): ...
class SynthesisError(AptitudeError): ...
class ExportError(AptitudeError): ...
class ValidationError(AptitudeError): ...
